name : sample go
on:
  push:
    branches: 
      - main
      - udmmaster
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code 
        uses: actions/checkout@v2

      - name: set up go
        uses: actions/setup-go@v3
        with: 
          go-version: '1.23'

      - name: build and run
        run: go run main.go